# delete tables
drop_processed_table = "DROP TABLE IF EXISTS processed_fire_incidents"
drop_curated_table = "DROP TABLE IF EXISTS curated_fire_incidents"

# create tables
create_curated_table = """
    CREATE TABLE curated_fire_incidents (
        incident_number VARCHAR(50) PRIMARY KEY,
        exposure_number INTEGER,
        id VARCHAR(50),
        address VARCHAR(200),
        incident_date TIMESTAMP,
        call_number VARCHAR(50),
        alarm_dttm TIMESTAMP,
        arrival_dttm TIMESTAMP,
        close_dttm TIMESTAMP,
        city VARCHAR(200),
        zipcode VARCHAR(20),
        battalion VARCHAR(50),
        station_area VARCHAR(50),
        box VARCHAR(20),
        suppression_units INTEGER,
        suppression_personnel INTEGER,
        ems_units INTEGER,
        ems_personnel INTEGER,
        other_units INTEGER,
        other_personnel INTEGER,
        first_unit_on_scene VARCHAR(200),
        estimated_property_loss INTEGER,
        estimated_contents_loss INTEGER,
        fire_fatalities INTEGER,
        fire_injuries INTEGER,
        civilian_fatalities INTEGER,
        civilian_injuries INTEGER,
        number_of_alarms INTEGER,
        primary_situation VARCHAR(200),
        mutual_aid VARCHAR(50),
        action_taken_primary VARCHAR(200),
        action_taken_secondary VARCHAR(200),
        action_taken_other VARCHAR(200),
        detector_alerted_occupants VARCHAR(50),
        property_use VARCHAR(200),
        area_of_fire_origin VARCHAR(200),
        ignition_cause VARCHAR(200),
        ignition_factor_primary VARCHAR(200),
        ignition_factor_secondary VARCHAR(200),
        heat_source VARCHAR(200),
        item_first_ignited VARCHAR(200),
        human_factors_associated_with_ignition VARCHAR(200),
        structure_type VARCHAR(200),
        structure_status VARCHAR(200),
        floor_of_fire_origin INTEGER,
        fire_spread VARCHAR(200),
        no_flame_spread VARCHAR(50),
        detectors_present VARCHAR(50),
        detector_type VARCHAR(200),
        detector_operation VARCHAR(200),
        detector_effectiveness VARCHAR(200),
        detector_failure_reason VARCHAR(200),
        automatic_extinguishing_system_present VARCHAR(50),
        supervisor_district VARCHAR(50),
        neighborhood_district VARCHAR(200),
        point GEOMETRY(POINT, 4326),
        data_as_of TIMESTAMP,
        data_loaded_at TIMESTAMP
    )
"""

create_processed_table = """
    CREATE TABLE processed_fire_incidents (
        incident_number VARCHAR(50) PRIMARY KEY,
        exposure_number INTEGER,
        id VARCHAR(50),
        address VARCHAR(200),
        incident_date TIMESTAMP,
        call_number VARCHAR(50),
        alarm_dttm TIMESTAMP,
        arrival_dttm TIMESTAMP,
        close_dttm TIMESTAMP,
        city VARCHAR(200),
        zipcode VARCHAR(20),
        battalion VARCHAR(50),
        station_area VARCHAR(50),
        box VARCHAR(20),
        suppression_units INTEGER,
        suppression_personnel INTEGER,
        ems_units INTEGER,
        ems_personnel INTEGER,
        other_units INTEGER,
        other_personnel INTEGER,
        first_unit_on_scene VARCHAR(200),
        estimated_property_loss INTEGER,
        estimated_contents_loss INTEGER,
        fire_fatalities INTEGER,
        fire_injuries INTEGER,
        civilian_fatalities INTEGER,
        civilian_injuries INTEGER,
        number_of_alarms INTEGER,
        primary_situation VARCHAR(200),
        mutual_aid VARCHAR(50),
        action_taken_primary VARCHAR(200),
        action_taken_secondary VARCHAR(200),
        action_taken_other VARCHAR(200),
        detector_alerted_occupants VARCHAR(50),
        property_use VARCHAR(200),
        area_of_fire_origin VARCHAR(200),
        ignition_cause VARCHAR(200),
        ignition_factor_primary VARCHAR(200),
        ignition_factor_secondary VARCHAR(200),
        heat_source VARCHAR(200),
        item_first_ignited VARCHAR(200),
        human_factors_associated_with_ignition VARCHAR(200),
        structure_type VARCHAR(200),
        structure_status VARCHAR(200),
        floor_of_fire_origin INTEGER,
        fire_spread VARCHAR(200),
        no_flame_spread VARCHAR(50),
        number_of_floors_with_minimum_damage INTEGER,
        number_of_floors_with_significant_damage INTEGER,
        number_of_floors_with_heavy_damage INTEGER,
        number_of_floors_with_extreme_damage INTEGER,
        detectors_present VARCHAR(50),
        detector_type VARCHAR(200),
        detector_operation VARCHAR(200),
        detector_effectiveness VARCHAR(200),
        detector_failure_reason VARCHAR(200),
        automatic_extinguishing_system_present VARCHAR(50),
        automatic_extinguishing_system_type VARCHAR(200),
        automatic_extinguishing_system_performance VARCHAR(200),
        automatic_extinguishing_system_failure_reason VARCHAR(200),
        number_of_sprinkler_heads_operating INTEGER,
        supervisor_district VARCHAR(50),
        neighborhood_district VARCHAR(200),
        point GEOMETRY(POINT, 4326),
        data_as_of TIMESTAMP,
        data_loaded_at TIMESTAMP
    )
"""

create_postgis_extension = "CREATE EXTENSION IF NOT EXISTS postgis;"


# Create indexes
query_index_battalion = "CREATE INDEX idx_battalion ON curated_fire_incidents(battalion)"
query_index_neighborhood_district = "CREATE INDEX idx_neighborhood_district ON curated_fire_incidents(neighborhood_district)"
query_index_supervisor_district = "CREATE INDEX idx_supervisor_district ON curated_fire_incidents(supervisor_district)"
query_index_incident_date = "CREATE INDEX idx_incident_date ON curated_fire_incidents(incident_date)"

# data transformation
# remove duplicated incident_number
# Remove columns that has >99,9% nulls
# 'number_of_floors_with_minimum_damage', 'number_of_floors_with_significant_damage', 'number_of_floors_with_heavy_damage', 
# 'number_of_floors_with_extreme_damage', 'automatic_extinguishing_system_type', 'automatic_extinguishing_system_performance', 
# 'automatic_extinguishing_system_failure_reason', 'number_of_sprinkler_heads_operating'
# 'point' column needs to be converted to geometry and set default value to (0, 0) if it is null

query_dedup = """
INSERT INTO curated_fire_incidents
with transformation as (
    SELECT 
        incident_number,
        row_number() over (PARTITION BY incident_number) AS row_num,
        exposure_number,
        id,
        address,
        incident_date,
        call_number,
        alarm_dttm,
        arrival_dttm,
        close_dttm,
        city,
        zipcode,
        battalion,
        station_area,
        box,
        suppression_units,
        suppression_personnel,
        ems_units,
        ems_personnel,
        other_units,
        other_personnel,
        first_unit_on_scene,
        estimated_property_loss,
        estimated_contents_loss,
        fire_fatalities,
        fire_injuries,
        civilian_fatalities,
        civilian_injuries,
        number_of_alarms,
        primary_situation,
        mutual_aid,
        action_taken_primary,
        action_taken_secondary,
        action_taken_other,
        detector_alerted_occupants,
        property_use,
        area_of_fire_origin,
        ignition_cause,
        ignition_factor_primary,
        ignition_factor_secondary,
        heat_source,
        item_first_ignited,
        human_factors_associated_with_ignition,
        structure_type,
        structure_status,
        floor_of_fire_origin,
        fire_spread,
        no_flame_spread,
        detectors_present,
        detector_type,
        detector_operation,
        detector_effectiveness,
        detector_failure_reason,
        automatic_extinguishing_system_present,
        supervisor_district,
        neighborhood_district,
        point,
        data_as_of,
        data_loaded_at
    FROM processed_fire_incidents
)
SELECT
    incident_number,
    exposure_number,
    id,
    address,
    incident_date,
    call_number,
    alarm_dttm,
    arrival_dttm,
    close_dttm,
    city,
    zipcode,
    battalion,
    station_area,
    box,
    suppression_units,
    suppression_personnel,
    ems_units,
    ems_personnel,
    other_units,
    other_personnel,
    first_unit_on_scene,
    estimated_property_loss,
    estimated_contents_loss,
    fire_fatalities,
    fire_injuries,
    civilian_fatalities,
    civilian_injuries,
    number_of_alarms,
    primary_situation,
    mutual_aid,
    action_taken_primary,
    action_taken_secondary,
    action_taken_other,
    detector_alerted_occupants,
    property_use,
    area_of_fire_origin,
    ignition_cause,
    ignition_factor_primary,
    ignition_factor_secondary,
    heat_source,
    item_first_ignited,
    human_factors_associated_with_ignition,
    structure_type,
    structure_status,
    floor_of_fire_origin,
    fire_spread,
    no_flame_spread,
    detectors_present,
    detector_type,
    detector_operation,
    detector_effectiveness,
    detector_failure_reason,
    automatic_extinguishing_system_present,
    supervisor_district,
    neighborhood_district,
    CASE
        WHEN point IS NULL OR point IN ('na', 'nan', '') THEN ST_SetSRID(ST_Point(0, 0), 4326)
        ELSE ST_SetSRID(ST_GeomFromText(point), 4326)
    END AS point,
    data_as_of,
    data_loaded_at
FROM transformation
WHERE row_num = 1
"""